# Generated by Django 5.0.6 on 2024-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='id',
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
